name: docx_template_fork
description: A Docx template engine.
version: 0.5.0
homepage: https://github.com/alexandremaillot/docx_template_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^4.0.4
  xml: ^6.5.0
  collection: ^1.19.1
  path: ^1.9.1
  pdf: ^3.10.7

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
